export { default as AmbientLight } from './AmbientLight';
export { default as DirectionalLight } from './DirectionalLight';
export { default as DirectionalLightWithHelper } from './DirectionalLightWithHelper';
export { default as HemisphereLight } from './HemisphereLight';
export { default as PointLight } from './PointLight';
export { default as PointLightWithHelper } from './PointLightWithHelper';
export { default as RectAreaLight } from './RectAreaLight';
export { default as SpotLight } from './SpotLight';
export { default as SpotLightWithHelper } from './SpotLightWithHelper';
